# metadati
metadati del documento:

{
    "REPORT NAME": "Elenco Regioni",
    "REPORT DESCRIZIONE": "Il report restituisce la lista delle regioni vigenti alla data selezionata e le loro principali caratteristiche o classificazioni statistico-amministrative disponibili.",
    "COL_DETAILS": [
        {
            "COLNAME": "COD_RIP",
            "LABEL": "Codice Ripartizione geografica",
            "NOTE": "Note non presenti",
            "LINK": "",
            "GUIDA": "Codice Istat della ripartizione geografica secondo la suddivisione del territorio nazionale in: 1) Nord-ovest, 2) Nord-est, 3) Centro, 4) Sud e 5) Isole.",
            "FORMATMASK": "",
            "FONTE": "Istat",
            "TYPE": "NUMBER"
        },
        {
            "COLNAME": "COD_REG",
            "LABEL": "Codice Regione",
            "NOTE": "Valore  di due caratteri alfanumerici, con validità nell'intervallo  01- 20.",
            "LINK": "",
            "GUIDA": "Codice Istat della regione",
            "FORMATMASK": "",
            "FONTE": "Istat",
            "TYPE": "VARCHAR"
        },
        {
            "COLNAME": "DEN_REG",
            "LABEL": "Regione",
            "NOTE": "Note non presenti",
            "LINK": "",
            "GUIDA": "Denominazione della regione",
            "FORMATMASK": "",
            "FONTE": "Istat",
            "TYPE": "VARCHAR"
        },

non la prendo 
    {
            "COLNAME": "TIPO_REG",
            "LABEL": "Flag tipo regione",
            "NOTE": "Note non presenti",
            "LINK": "",
            "GUIDA": "Descrizione Ente: 1= Regione a Statuto ordinario; 2=Regione a Statuto speciale",
            "FORMATMASK": "",
            "FONTE": "Istat",
            "TYPE": "VARCHAR"
        },
non la prendo 
        {
            "COLNAME": "DESC_TIPO_REG",
            "LABEL": "Tipo regione",
            "NOTE": "Note non presenti",
            "LINK": "",
            "GUIDA": "Regione a statuto ordinario o Regione a statuto speciale",
            "FORMATMASK": "",
            "FONTE": "Istat",
            "TYPE": "VARCHAR"
        },

non la prendo 
        {
            "COLNAME": "DEN_RIP",
            "LABEL": "Ripartizione geografica",
            "NOTE": "Note non presenti",
            "LINK": "",
            "GUIDA": "Denominazione della ripartizione geografica  secondo la suddivisione del territorio nazionale in 5 ambiti: Nord-ovest, Nord-est, Centro, Sud e Isole.",
            "FORMATMASK": "",
            "FONTE": "Istat",
            "TYPE": "VARCHAR"
        },
        
non la prendo 
        {
            "COLNAME": "COD_REG_FISCALE",
            "LABEL": "Codice fiscale",
            "NOTE": "Codice di 11 caratteri in formato testo",
            "LINK": "",
            "GUIDA": "Codice attribuito dall’Agenzia delle Entrate al fine di identificare in modo univoco un soggetto giuridico",
            "FORMATMASK": "",
            "FONTE": "Agenzia delle Entrate",
            "TYPE": "VARCHAR"
        },

non la prendo 
        {
            "COLNAME": "COD_NUTS2_2010",
            "LABEL": "Codice NUTS2 2010",
            "NOTE": "Cfr. Regolamenti (UE) della Commissione n. 31/2011, n. 1319/2013 e n. 2066/2016. Nella nomenclatura NUTS non è presente la regione di livello 2 \"Trentino-Alto Adige/Südtirol\", al suo posto compaiono la \"Provincia autonoma di Bolzano/Bozen\" (ITH1) e la \"Provincia autonoma di Trento\" (ITH2).",
            "LINK": "https://ec.europa.eu/eurostat/web/nuts/history",
            "GUIDA": "Nomenclatura delle unità territoriali europee (NUTS2) corrispondente al livello territoriale delle regioni, valida dal 2010 al 2020",
            "FORMATMASK": "",
            "FONTE": "Eurostat",
            "TYPE": "VARCHAR"
        }
    ]
}

In [1]:
# =============================================================
# =============================================================
#
# librerie di base
import numpy as np
import pandas as pd

In [2]:
# =============================================================
# =============================================================
#
# importo le funzioni personali per uso comune

#aggiunto quando ho spostato i file in una cartella a parte
import sys
sys.path.append("./Moduli")

import Moduli.Modulo_Common as pd_common

In [3]:
df_regioni = pd.read_csv( pd_common.GetFolderDati()+ "//Dati_Regione_All.csv")

In [4]:
df_regioni.head(5)

,Unnamed: 0.1,Unnamed: 0,COD_RIP,COD_REG,DEN_REG,DEN_RIP,TIPO_REG,DESC_TIPO_REG,COD_REG_FISCALE,COD_NUTS2_2010,anno_riferimento,COD_NUTS2_2021,COD_NUTS2_2024
0,0,0,1,1,Piemonte,Nord-ovest,1,Regione a Statuto ordinario,80087670016,ITC1,2010,NaN,NaN
1,1,1,1,2,Valle d'Aosta/Vallée d'Aoste,Nord-ovest,2,Regione a Statuto speciale,80002270074,ITC2,2010,NaN,NaN
2,2,2,1,3,Lombardia,Nord-ovest,1,Regione a Statuto ordinario,80050050154,ITC4,2010,NaN,NaN
3,3,3,2,4,Trentino-Alto Adige/Südtirol,Nord-est,2,Regione a Statuto speciale,80003690221,NaN,2010,NaN,NaN
4,4,4,2,5,Veneto,Nord-est,1,Regione a Statuto ordinario,80007580279,ITH3,2010,NaN,NaN

In [5]:
df_regioni.columns

Index(['Unnamed: 0.1', 'Unnamed: 0', 'COD_RIP', 'COD_REG', 'DEN_REG',
       'DEN_RIP', 'TIPO_REG', 'DESC_TIPO_REG', 'COD_REG_FISCALE',
       'COD_NUTS2_2010', 'anno_riferimento', 'COD_NUTS2_2021',
       'COD_NUTS2_2024'],
      dtype='object')

In [6]:
df_regioni_EDA = df_regioni.copy()

In [7]:
df_regioni_EDA.head(2)

,Unnamed: 0.1,Unnamed: 0,COD_RIP,COD_REG,DEN_REG,DEN_RIP,TIPO_REG,DESC_TIPO_REG,COD_REG_FISCALE,COD_NUTS2_2010,anno_riferimento,COD_NUTS2_2021,COD_NUTS2_2024
0,0,0,1,1,Piemonte,Nord-ovest,1,Regione a Statuto ordinario,80087670016,ITC1,2010,NaN,NaN
1,1,1,1,2,Valle d'Aosta/Vallée d'Aoste,Nord-ovest,2,Regione a Statuto speciale,80002270074,ITC2,2010,NaN,NaN

In [8]:
# come indicato nella prima sezione, mi tengo le colonne di interesse
df_regioni_EDA = df_regioni_EDA[['anno_riferimento','COD_RIP', 'COD_REG', 'DEN_REG' ]]

In [9]:
df_regioni_EDA['COD_RIP'].unique()

array([1, 2, 3, 4, 5])

In [10]:
df_regioni_EDA['COD_REG'].unique()

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [11]:
df_regioni_EDA.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 340 entries, 0 to 339
Data columns (total 4 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   anno_riferimento  340 non-null    int64
 1   COD_RIP           340 non-null    int64
 2   COD_REG           340 non-null    int64
 3   DEN_REG           340 non-null    object
dtypes: int64(3), object(1)
memory usage: 10.8+ KB

In [12]:
# a) tipo dato corretto
# b) non sono presenti colonne nulle

In [13]:
df_regioni_EDA.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 340 entries, 0 to 339
Data columns (total 4 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   anno_riferimento  340 non-null    int64
 1   COD_RIP           340 non-null    int64
 2   COD_REG           340 non-null    int64
 3   DEN_REG           340 non-null    object
dtypes: int64(3), object(1)
memory usage: 10.8+ KB

In [14]:
df_regioni_EDA.groupby(['anno_riferimento'])['COD_REG'].agg('count')

anno_riferimento
2010    20
2011    20
2012    20
2013    20
2014    20
2015    20
2016    20
2017    20
2018    20
2019    20
2020    20
2021    20
2022    20
2023    20
2024    20
2025    20
2026    20
Name: COD_REG, dtype: int64

In [15]:
len(df_regioni_EDA.COD_REG.unique())

20

In [16]:
df_regioni_EDA[df_regioni_EDA.COD_REG==1]

     anno_riferimento  COD_RIP  COD_REG   DEN_REG
0                2010        1        1  Piemonte
20               2011        1        1  Piemonte
40               2012        1        1  Piemonte
60               2013        1        1  Piemonte
80               2014        1        1  Piemonte
100              2015        1        1  Piemonte
120              2016        1        1  Piemonte
140              2017        1        1  Piemonte
160              2018        1        1  Piemonte
180              2019        1        1  Piemonte
200              2020        1        1  Piemonte
220              2021        1        1  Piemonte
240              2022        1        1  Piemonte
260              2023        1        1  Piemonte
280              2024        1        1  Piemonte
300              2025        1        1  Piemonte
320              2026        1        1  Piemonte

In [17]:
#SALVO IL DATASET FINALE

pd_common.SalvaDataset(df_regioni_EDA, f"ElencoRegioni",False)

      path completo file:  c:\progetto_dataanalyst\progettofinale\Analisi/ElencoRegioni.csv
         Il file 'c:\progetto_dataanalyst\progettofinale\Analisi/ElencoRegioni.csv' esiste, per cui lo rimuovo
      Il file salvato c:\progetto_dataanalyst\progettofinale\Analisi/ElencoRegioni.csv