# metadati

la descrizione dei campi è stata presa dal formato xml in cui era presente lo schema
DATAFLOW,
FREQ,
REF_AREA,
DATA_TYPE,
RESULT,
TIME_PERIOD,        --> anno di riferimento (dal 2001)
                        si mantiene
OBS_VALUE,
OBS_STATUS,
NOTE_DS,
NOTE_REF_AREA,
NOTE_DATA_TYPE,
NOTE_RESULT,
NOTE_TIME_PERIOD,
BASE_PER,
UNIT_MEAS,
UNIT_MULT

In [1]:
# =============================================================
# =============================================================
#
# librerie di base
import numpy as np
import pandas as pd

In [2]:
# =============================================================
# =============================================================
#
# importo le funzioni personali creati per questa fase


#aggiunto quando ho spostato i file in una cartella a parte
import sys
sys.path.append("./Moduli")

#import Moduli.Modulo_Fase_02 as pd_fase1

In [3]:
# =============================================================
# =============================================================
#
# importo le funzioni personali per uso comune
import Moduli.Modulo_Common as pd_common

In [4]:
# =============================================================
# =============================================================
#
# importo le funzioni personali per uso comune
import Moduli.Modulo_Configurazione as pd_config

In [5]:
df_incidenti = pd.read_csv( pd_common.GetFolderDati()+ "//Dati_Incidenti.csv")

In [6]:
df_incidenti.head(5)

,Unnamed: 0,DATAFLOW,FREQ,REF_AREA,DATA_TYPE,RESULT,TIME_PERIOD,OBS_VALUE,OBS_STATUS,NOTE_DS,NOTE_REF_AREA,NOTE_DATA_TYPE,NOTE_RESULT,NOTE_TIME_PERIOD,BASE_PER,UNIT_MEAS,UNIT_MULT
0,0,IT1:41_983(1.0),A,1001,KILLINJ,F,2001,10,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,1,IT1:41_983(1.0),A,1001,KILLINJ,F,2002,10,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,2,IT1:41_983(1.0),A,1001,KILLINJ,F,2003,7,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,3,IT1:41_983(1.0),A,1001,KILLINJ,F,2004,13,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,4,IT1:41_983(1.0),A,1001,KILLINJ,F,2005,2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [6]:
df_incidenti_analisi= df_incidenti.copy()

In [7]:
df_incidenti_analisi.FREQ.unique()

array(['A'], dtype=object)

In [8]:
df_incidenti_analisi.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 573552 entries, 0 to 573551
Data columns (total 17 columns):
 #   Column            Non-Null Count   Dtype
---  ------            --------------   -----
 0   Unnamed: 0        573552 non-null  int64
 1   DATAFLOW          573552 non-null  object
 2   FREQ              573552 non-null  object
 3   REF_AREA          573552 non-null  int64
 4   DATA_TYPE         573552 non-null  object
 5   RESULT            573552 non-null  object
 6   TIME_PERIOD       573552 non-null  int64
 7   OBS_VALUE         573552 non-null  int64
 8   OBS_STATUS        0 non-null       float64
 9   NOTE_DS           0 non-null       float64
 10  NOTE_REF_AREA     0 non-null       float64
 11  NOTE_DATA_TYPE    0 non-null       float64
 12  NOTE_RESULT       0 non-null       float64
 13  NOTE_TIME_PERIOD  0 non-null       float64
 14  BASE_PER          0 non-null       float64
 15  UNIT_MEAS         0 non-null       float64
 16  UNIT_MULT         0 non-null       float64
dtypes: float64(9), int64(4), object(4)
memory usage: 74.4+ MB

In [9]:
#rimozione campi vuoti 
df_incidenti_analisi = df_incidenti_analisi.drop('OBS_STATUS',axis=1)
df_incidenti_analisi = df_incidenti_analisi.drop('NOTE_DS',axis=1)
df_incidenti_analisi = df_incidenti_analisi.drop('NOTE_REF_AREA',axis=1)
df_incidenti_analisi = df_incidenti_analisi.drop('NOTE_DATA_TYPE',axis=1)
df_incidenti_analisi = df_incidenti_analisi.drop('NOTE_RESULT',axis=1)
df_incidenti_analisi = df_incidenti_analisi.drop('NOTE_TIME_PERIOD',axis=1)
df_incidenti_analisi = df_incidenti_analisi.drop('BASE_PER',axis=1)
df_incidenti_analisi = df_incidenti_analisi.drop('UNIT_MEAS',axis=1)
df_incidenti_analisi = df_incidenti_analisi.drop('UNIT_MULT',axis=1)

In [10]:
df_incidenti_analisi.FREQ.unique()

array(['A'], dtype=object)

In [11]:
#rimozione campi costanti
df_incidenti_analisi = df_incidenti_analisi.drop('FREQ',axis=1)

In [12]:
df_incidenti_analisi.DATAFLOW.unique()

array(['IT1:41_983(1.0)'], dtype=object)

In [13]:
#rimozione campi costanti
df_incidenti_analisi = df_incidenti_analisi.drop('DATAFLOW',axis=1)

In [14]:
df_incidenti_analisi.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 573552 entries, 0 to 573551
Data columns (total 6 columns):
 #   Column       Non-Null Count   Dtype
---  ------       --------------   -----
 0   Unnamed: 0   573552 non-null  int64
 1   REF_AREA     573552 non-null  int64
 2   DATA_TYPE    573552 non-null  object
 3   RESULT       573552 non-null  object
 4   TIME_PERIOD  573552 non-null  int64
 5   OBS_VALUE    573552 non-null  int64
dtypes: int64(4), object(2)
memory usage: 26.3+ MB

In [15]:
df_incidenti_analisi.head(2)

   Unnamed: 0  REF_AREA DATA_TYPE RESULT  TIME_PERIOD  OBS_VALUE
0           0      1001   KILLINJ      F         2001         10
1           1      1001   KILLINJ      F         2002         10

In [16]:
df_incidenti_analisi.RESULT.unique()

array(['F', 'M', '9'], dtype=object)

In [17]:
#IL DATO TIPO 9 SONO I TOTALI, li rimuovo dal datase
df_incidenti_analisi = df_incidenti_analisi[df_incidenti_analisi['RESULT']!='9']

In [18]:
df_incidenti_analisi.info()

<class 'pandas.core.frame.DataFrame'>
Index: 382368 entries, 0 to 573543
Data columns (total 6 columns):
 #   Column       Non-Null Count   Dtype
---  ------       --------------   -----
 0   Unnamed: 0   382368 non-null  int64
 1   REF_AREA     382368 non-null  int64
 2   DATA_TYPE    382368 non-null  object
 3   RESULT       382368 non-null  object
 4   TIME_PERIOD  382368 non-null  int64
 5   OBS_VALUE    382368 non-null  int64
dtypes: int64(4), object(2)
memory usage: 20.4+ MB

In [19]:
df_incidenti_analisi.DATA_TYPE.unique()

array(['KILLINJ'], dtype=object)

In [20]:
#rimozione campi costanti
df_incidenti_analisi = df_incidenti_analisi.drop('DATA_TYPE',axis=1)

In [21]:
df_incidenti_analisi.count()

Unnamed: 0     382368
REF_AREA       382368
RESULT         382368
TIME_PERIOD    382368
OBS_VALUE      382368
dtype: int64

In [22]:
df_incidenti_analisi.info()

<class 'pandas.core.frame.DataFrame'>
Index: 382368 entries, 0 to 573543
Data columns (total 5 columns):
 #   Column       Non-Null Count   Dtype
---  ------       --------------   -----
 0   Unnamed: 0   382368 non-null  int64
 1   REF_AREA     382368 non-null  int64
 2   RESULT       382368 non-null  object
 3   TIME_PERIOD  382368 non-null  int64
 4   OBS_VALUE    382368 non-null  int64
dtypes: int64(4), object(1)
memory usage: 17.5+ MB

In [ ]:
#tipo dati corretto CON LA VERSIONE PYTHON ULTIMA, MENTRE CON QUELLA ANACONDA (VERSIONE PREDENTE CAMBIATO IL FORMATO STR IN OBJECT)
#non faccio nulla --> CAMBIO DOPO

In [23]:
df_incidenti_analisi['RESULT_DESC']='Feriti'

In [24]:
df_incidenti_analisi.loc[df_incidenti_analisi['RESULT'] == 'M', ['RESULT_DESC']] = 'Morti'

In [25]:
df_incidenti_analisi.RESULT.unique()

array(['F', 'M'], dtype=object)

In [26]:
df_incidenti_analisi.RESULT_DESC.unique()

array(['Feriti', 'Morti'], dtype=object)

In [32]:
df_incidenti_analisi.groupby(['RESULT','RESULT_DESC'])['OBS_VALUE'].agg('count')

RESULT  RESULT_DESC
F       Feriti         191184
M       Morti          191184
Name: OBS_VALUE, dtype: int64

In [44]:
#verifico
df_incidenti_analisi.info()

<class 'pandas.core.frame.DataFrame'>
Index: 77780 entries, 14 to 573537
Data columns (total 6 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   Unnamed: 0   77780 non-null  int64
 1   REF_AREA     77780 non-null  int64
 2   RESULT       77780 non-null  object
 3   TIME_PERIOD  77780 non-null  int64
 4   OBS_VALUE    77780 non-null  int64
 5   RESULT_DESC  77780 non-null  object
dtypes: int64(4), object(2)
memory usage: 4.2+ MB

In [33]:
#df_incidenti_analisi["RESULT"] = df_incidenti_analisi["RESULT"].astype('str')
df_incidenti_analisi["RESULT"] = df_incidenti_analisi["RESULT"].astype('string')

In [34]:
df_incidenti_analisi["RESULT_DESC"] = df_incidenti_analisi["RESULT_DESC"].astype('string')

In [35]:
#verifico
df_incidenti_analisi.info()

<class 'pandas.core.frame.DataFrame'>
Index: 382368 entries, 0 to 573543
Data columns (total 6 columns):
 #   Column       Non-Null Count   Dtype
---  ------       --------------   -----
 0   Unnamed: 0   382368 non-null  int64
 1   REF_AREA     382368 non-null  int64
 2   RESULT       382368 non-null  string
 3   TIME_PERIOD  382368 non-null  int64
 4   OBS_VALUE    382368 non-null  int64
 5   RESULT_DESC  382368 non-null  string
dtypes: int64(4), string(2)
memory usage: 20.4 MB

In [30]:
#lettura dati relativi al OBS_VALUE
df_incidenti_analisi.OBS_VALUE.describe()

count    382368.000000
mean         17.812605
std         239.711176
min           0.000000
25%           0.000000
50%           1.000000
75%           5.000000
max       30254.000000
Name: OBS_VALUE, dtype: float64

In [31]:
df_incidenti_analisi[df_incidenti_analisi.OBS_VALUE== 30254]

        Unnamed: 0  REF_AREA RESULT  TIME_PERIOD  OBS_VALUE RESULT_DESC
348588      348588     58091      F         2004      30254      Feriti

In [36]:
#rimuovo i casi non significativi
print(f'tot rec: {df_incidenti_analisi.REF_AREA.count()}') #382368
rec_mag_0 = df_incidenti_analisi[df_incidenti_analisi.OBS_VALUE> 0].REF_AREA.count()
rec_equ_0 = df_incidenti_analisi[df_incidenti_analisi.OBS_VALUE== 0].REF_AREA.count()
print(f'rec >0: {rec_mag_0}')
print(f'rec =0: {rec_equ_0}')
print(f'tot derivato: {rec_equ_0+rec_mag_0}')

tot rec: 382368
rec >0: 194998
rec =0: 187370
tot derivato: 382368

In [37]:
df_incidenti_analisi=df_incidenti_analisi[df_incidenti_analisi.OBS_VALUE> 0]

In [38]:
#lettura dati relativi al OBS_VALUE
df_incidenti_analisi.OBS_VALUE.describe()

count    194998.000000
mean         34.928410
std         334.779855
min           1.000000
25%           2.000000
50%           5.000000
75%          18.000000
max       30254.000000
Name: OBS_VALUE, dtype: float64

In [39]:
df_incidenti_analisi.TIME_PERIOD.unique()

array([2001, 2002, 2003, 2004, 2005, 2006, 2007, 2008, 2009, 2010, 2011,
       2012, 2013, 2014, 2015, 2016, 2018, 2019, 2020, 2021, 2022, 2023,
       2024, 2017])

In [41]:
pd_config.GetAnnoInizioAnalisi()

2015

In [40]:
df_incidenti_analisi = df_incidenti_analisi[df_incidenti_analisi.TIME_PERIOD  >= pd_config.GetAnnoInizioAnalisi()]

In [41]:
df_incidenti_analisi.TIME_PERIOD.unique()

array([2015, 2016, 2018, 2019, 2020, 2021, 2022, 2023, 2024, 2017])

In [42]:
df_incidenti_analisi.head(5)

    Unnamed: 0  REF_AREA RESULT  TIME_PERIOD  OBS_VALUE RESULT_DESC
14          14      1001      F         2015          9      Feriti
15          15      1001      F         2016          8      Feriti
17          17      1001      F         2018          1      Feriti
18          18      1001      F         2019          5      Feriti
19          19      1001      F         2020          4      Feriti

In [43]:
#SALVO IL DATASET FINALE

pd_common.SalvaDataset(df_incidenti_analisi, f"ElencoIncidenti",False)

      path completo file:  c:\progetto_dataanalyst\progettofinale\Analisi/ElencoIncidenti.csv
         Il file 'c:\progetto_dataanalyst\progettofinale\Analisi/ElencoIncidenti.csv' esiste, per cui lo rimuovo
      Il file salvato c:\progetto_dataanalyst\progettofinale\Analisi/ElencoIncidenti.csv

In [73]:
dftipoevento = df_incidenti_analisi.groupby(['RESULT','RESULT_DESC'], as_index=False).size()
#['OBS_VALUE'].agg('count')

In [74]:
dftipoevento.head()

  RESULT RESULT_DESC   size
0      F      Feriti  61588
1      M       Morti  16192

In [75]:
dftipoevento =dftipoevento[['RESULT','RESULT_DESC']]

In [76]:
dftipoevento

  RESULT RESULT_DESC
0      F      Feriti
1      M       Morti

In [78]:
dftipoevento.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2 entries, 0 to 1
Data columns (total 2 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   RESULT       2 non-null      string
 1   RESULT_DESC  2 non-null      string
dtypes: string(2)
memory usage: 164.0 bytes

In [77]:
pd_common.SalvaDataset(dftipoevento, f"TipoEvento",False)

      path completo file:  c:\progetto_dataanalyst\progettofinale\Analisi/TipoEvento.csv
         Il file 'c:\progetto_dataanalyst\progettofinale\Analisi/TipoEvento.csv' esiste, per cui lo rimuovo
      Il file salvato c:\progetto_dataanalyst\progettofinale\Analisi/TipoEvento.csv