In [28]:
import pandas as pd
import numpy as np

In [3]:
# =============================================================
# =============================================================
#
# importo le funzioni personali per uso comune

#aggiunto quando ho spostato i file in una cartella a parte
import sys
sys.path.append("./Moduli")

import Moduli.Modulo_Common as pd_common

In [4]:
# =============================================================
# =============================================================
#
# importo le funzioni personali creati per questa fase


import Moduli.Modulo_Configurazione as pd_config

In [6]:
#scelta di fare il calendario da codice per imparare ad usare python
# infatti per fare il codice ho impegato tanto tempo
datainizio=f'{str(pd_config.GetAnnoInizioAnalisi())}-01-01'
datafine=f'{str(pd_config.GetAnnoInizioAnalisi() + pd_config.GetNrAnniAnalisi())}-12-31'

print(f'datainizio: {datainizio} - datafine: {datafine}' )
#crea un dataframe con 1 colonna con il range di date da a
dfcalendario = pd.DataFrame({"Data": pd.date_range(datainizio, datafine)})

datainizio: 2015-01-01 - datafine: 2026-12-31

In [7]:
#aggiungo colonna indice
dfcalendario = dfcalendario.reset_index()

In [8]:
dfcalendario.head(5)

   index       Data
0      0 2015-01-01
1      1 2015-01-02
2      2 2015-01-03
3      3 2015-01-04
4      4 2015-01-05

In [10]:
#aggiungo le colonne legate al tempo per le analisi e filtri
dfcalendario["Anno"] = dfcalendario.Data.dt.year
dfcalendario["Mese"] = dfcalendario.Data.dt.month
dfcalendario["Giorno"] = dfcalendario.Data.dt.day
#dfcalendario["GG_name"] = dfcalendario.Data.dt.day_name
#0/1/2
# get the day of the week (Note: Monday is coded as 0, and Sunday as 6)
dfcalendario["GGSettimana"] = dfcalendario.Data.dt.day_of_week #STESSO VALORE DI dfcalendario.Data.dt.weekday
#il nome del giorno della settimana
dfcalendario["GGSettimanaDsc"] = "LUN"


#non va dfcalendario["MeseDesc"] = dfcalendario.Data.dt.month_name
dfcalendario["GGDelMese"] = dfcalendario.Data.dt.days_in_month

In [8]:
#aggiorna il datase --> fa schivo ma si migliora quando si ha tempo
def AssegnaGiorno(giornoSettimana:int,nomeDelGiorno:str):
  MASCHERA_DATI = dfcalendario["GGSettimana"]==giornoSettimana
  dfcalendario.loc[MASCHERA_DATI,"GGSettimanaDsc"]=nomeDelGiorno

In [9]:
dfcalendario[(dfcalendario.Anno==2026) &
              (dfcalendario.Mese==5) &
              (dfcalendario.Giorno==13)]

,index,Data,Anno,Mese,Giorno,GGSettimana,GGSettimanaDsc,GGDelMese
4150,4150,2026-05-13,2026,5,13,2,LUN,31

In [11]:
AssegnaGiorno(1,"MAR")
AssegnaGiorno(2,"MER")
AssegnaGiorno(3,"GIO")
AssegnaGiorno(4,"VEN")
AssegnaGiorno(5,"SAB")
AssegnaGiorno(6,"DOM")

In [10]:
dfcalendario[(dfcalendario.Anno==2026) &
              (dfcalendario.Mese==5) &
              (dfcalendario.Giorno==13)]

,index,Data,Anno,Mese,Giorno,GGSettimana,GGSettimanaDsc,GGDelMese
4150,4150,2026-05-13,2026,5,13,2,LUN,31

In [11]:
dfcalendario[(dfcalendario.Anno==2026) &
              (dfcalendario.Mese==5) &
              (dfcalendario.Giorno==12)]

,index,Data,Anno,Mese,Giorno,GGSettimana,GGSettimanaDsc,GGDelMese
4149,4149,2026-05-12,2026,5,12,1,LUN,31

In [12]:
dfcalendario.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4383 entries, 0 to 4382
Data columns (total 8 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   index           4383 non-null   int64
 1   Data            4383 non-null   datetime64[ns]
 2   Anno            4383 non-null   int32
 3   Mese            4383 non-null   int32
 4   Giorno          4383 non-null   int32
 5   GGSettimana     4383 non-null   int32
 6   GGSettimanaDsc  4383 non-null   object
 7   GGDelMese       4383 non-null   int32
dtypes: datetime64[ns](1), int32(5), int64(1), object(1)
memory usage: 188.5+ KB

In [13]:
#GESTIONE STAGIONE DELL'ANNO
dfcalendario["Stagione"]="Primavera"
def AssegnaStagione(mese:int,stagione:str):
  MASCHERA_DATI = dfcalendario["Mese"]==mese
  dfcalendario.loc[MASCHERA_DATI,"Stagione"]=stagione

In [14]:
AssegnaStagione(6,'Estate')#: giugno, luglio, agosto.
AssegnaStagione(7,'Estate')#: giugno, luglio, agosto.
AssegnaStagione(8,'Estate')#: giugno, luglio, agosto.

AssegnaStagione(9,'Autunno')#: Autunno: settembre, ottobre, novembre
AssegnaStagione(10,'Autunno')#:
AssegnaStagione(11,'Autunno')#:

AssegnaStagione(12,'Inverno')#:Inverno: dicembre, gennaio, febbraio
AssegnaStagione(1,'Inverno')#:Inverno: dicembre, gennaio, febbraio
AssegnaStagione(2,'Inverno')#:Inverno: dicembre, gennaio, febbraio

In [15]:
dfcalendario.sample(5)

,index,Data,Anno,Mese,Giorno,GGSettimana,GGSettimanaDsc,GGDelMese,Stagione
3680,3680,2025-01-28,2025,1,28,1,LUN,31,Inverno
1819,1819,2019-12-25,2019,12,25,2,LUN,31,Inverno
1691,1691,2019-08-19,2019,8,19,0,LUN,31,Estate
3944,3944,2025-10-19,2025,10,19,6,LUN,31,Autunno
1174,1174,2018-03-20,2018,3,20,1,LUN,31,Primavera

In [16]:
dfcalendario.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4383 entries, 0 to 4382
Data columns (total 9 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   index           4383 non-null   int64
 1   Data            4383 non-null   datetime64[ns]
 2   Anno            4383 non-null   int32
 3   Mese            4383 non-null   int32
 4   Giorno          4383 non-null   int32
 5   GGSettimana     4383 non-null   int32
 6   GGSettimanaDsc  4383 non-null   object
 7   GGDelMese       4383 non-null   int32
 8   Stagione        4383 non-null   object
dtypes: datetime64[ns](1), int32(5), int64(1), object(2)
memory usage: 222.7+ KB

In [17]:
#voglio distingure il weekend (SAB-DOM) dagli altri gg
dfcalendario['FlgWeekend'] = False

In [18]:
#solo per sab e dom assegno il true
dfcalendario.loc[ (dfcalendario["GGSettimana"]==5) | (dfcalendario["GGSettimana"]==6),
                 'FlgWeekend'] = True

In [19]:
dfcalendario.sample(5)

,index,Data,Anno,Mese,Giorno,GGSettimana,GGSettimanaDsc,GGDelMese,Stagione,FlgWeekend
684,684,2016-11-15,2016,11,15,1,LUN,30,Autunno,False
4349,4349,2026-11-28,2026,11,28,5,LUN,30,Autunno,True
1132,1132,2018-02-06,2018,2,6,1,LUN,28,Inverno,False
3528,3528,2024-08-29,2024,8,29,3,LUN,31,Estate,False
467,467,2016-04-12,2016,4,12,1,LUN,30,Primavera,False

In [20]:
dfcalendario.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4383 entries, 0 to 4382
Data columns (total 10 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   index           4383 non-null   int64
 1   Data            4383 non-null   datetime64[ns]
 2   Anno            4383 non-null   int32
 3   Mese            4383 non-null   int32
 4   Giorno          4383 non-null   int32
 5   GGSettimana     4383 non-null   int32
 6   GGSettimanaDsc  4383 non-null   object
 7   GGDelMese       4383 non-null   int32
 8   Stagione        4383 non-null   object
 9   FlgWeekend      4383 non-null   bool
dtypes: bool(1), datetime64[ns](1), int32(5), int64(1), object(2)
memory usage: 227.0+ KB

In [45]:
dfcalendario["GGSettimanaDsc"] = dfcalendario["GGSettimanaDsc"].astype(str)
dfcalendario["GGSettimanaDsc"] = dfcalendario["GGSettimanaDsc"].astype('string')

In [46]:
dfcalendario.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4383 entries, 0 to 4382
Data columns (total 10 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   index           4383 non-null   int64
 1   Data            4383 non-null   datetime64[ns]
 2   Anno            4383 non-null   int32
 3   Mese            4383 non-null   int32
 4   Giorno          4383 non-null   int32
 5   GGSettimana     4383 non-null   int32
 6   GGSettimanaDsc  4383 non-null   string
 7   GGDelMese       4383 non-null   int32
 8   Stagione        4383 non-null   string
 9   FlgWeekend      4383 non-null   bool
dtypes: bool(1), datetime64[ns](1), int32(5), int64(1), string(2)
memory usage: 227.0 KB

In [ ]:
#dfcalendario["Stagione"] = dfcalendario["Stagione"].astype('str')
dfcalendario["Stagione"] = dfcalendario["Stagione"].astype('string')

In [44]:
dfcalendario.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4383 entries, 0 to 4382
Data columns (total 10 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   index           4383 non-null   int64
 1   Data            4383 non-null   datetime64[ns]
 2   Anno            4383 non-null   int32
 3   Mese            4383 non-null   int32
 4   Giorno          4383 non-null   int32
 5   GGSettimana     4383 non-null   int32
 6   GGSettimanaDsc  4383 non-null   object
 7   GGDelMese       4383 non-null   int32
 8   Stagione        4383 non-null   string
 9   FlgWeekend      4383 non-null   bool
dtypes: bool(1), datetime64[ns](1), int32(5), int64(1), object(1), string(1)
memory usage: 227.0+ KB

In [47]:
#SALVO IL DATASET FINALE

pd_common.SalvaDataset(dfcalendario, f"Calendario",False)

      path completo file:  c:\progetto_dataanalyst\progettofinale\Analisi/Calendario.csv
         Il file 'c:\progetto_dataanalyst\progettofinale\Analisi/Calendario.csv' esiste, per cui lo rimuovo
      Il file salvato c:\progetto_dataanalyst\progettofinale\Analisi/Calendario.csv

In [20]:
#mi sono accorto che il report incidenti ha la dimensione temporale basata solo sull'anno...
dfanno = pd.DataFrame(dfcalendario['Anno'].unique(),columns=['Anno'])

In [21]:
#aggiungo anno di forecast
dfforecast = pd.DataFrame([2027], columns=dfanno.columns)

In [22]:
dfforecast.head()

   Anno
0  2027

In [26]:
dfanno.head()

   Anno
0  2015
1  2016
2  2017
3  2018
4  2019

In [29]:
dfanno = pd.concat( [dfanno, dfforecast], ignore_index=True)

In [30]:
dfanno

    Anno
0   2015
1   2016
2   2017
3   2018
4   2019
5   2020
6   2021
7   2022
8   2023
9   2024
10  2025
11  2026
12  2027

In [31]:

pd_common.SalvaDataset(dfanno, f"Annualita",False)

      path completo file:  c:\progetto_dataanalyst\progettofinale\Analisi/Annualita.csv
         Il file 'c:\progetto_dataanalyst\progettofinale\Analisi/Annualita.csv' esiste, per cui lo rimuovo
      Il file salvato c:\progetto_dataanalyst\progettofinale\Analisi/Annualita.csv