# metadati
metadati del documento:
link preso: vedere 01_d_recupero_fonti_dati

{
    "REPORT NAME": "Elenco Ripartizioni geografiche",
    "REPORT DESCRIZIONE": "Il report restituisce la lista delle ripartizioni geografiche valide alla data selezionata e la relativa dimensione in termini di numerosità di unità territoriali sotto ordinate. Ciascuna ripartizione è identificata dalla denominazione e dal codice statistico.",
    "COL_DETAILS": [
        {
            "COLNAME": "COD_RIP",
            "LABEL": "Codice Ripartizione geografica",
            "NOTE": "Note non presenti",
            "LINK": "",
            "GUIDA": "Codice Istat della Ripartizione geografica secondo la suddivisione del territorio nazionale in: 1) Nord-ovest, 2) Nord-est, 3) Centro, 4) Sud e 5) Isole.",
            "FORMATMASK": "",
            "FONTE": "Istat",
            "TYPE": "NUMBER"
        },
        {
            "COLNAME": "DEN_RIP",
            "LABEL": "Ripartizione geografica",
            "NOTE": "Note non presenti",
            "LINK": "",
            "GUIDA": "Denominazione della Ripartizione geografica  secondo la suddivisione del territorio nazionale in 5 ambiti: Nord-ovest, Nord-est, Centro, Sud e Isole.",
            "FORMATMASK": "",
            "FONTE": "Istat",
            "TYPE": "VARCHAR"
        },

non la considero
        {
            "COLNAME": "N_COMP",
            "LABEL": "Numero compartimenti",
            "NOTE": "Note non presenti",
            "LINK": "",
            "GUIDA": "Numero di compartimenti per ripartizione geografica",
            "FORMATMASK": "999G999G999G999G999G999G990",
            "FONTE": "Istat",
            "TYPE": "NUMBER"
        },

        
non la considero
        {
            "COLNAME": "N_PROV",
            "LABEL": "Numero province",
            "NOTE": "Note non presenti",
            "LINK": "",
            "GUIDA": "Numero di province per ripartizione geografica",
            "FORMATMASK": "999G999G999G999G999G999G990",
            "FONTE": "Istat",
            "TYPE": "NUMBER"
        },


non la considero
        {
            "COLNAME": "N_CIR_DIS",
            "LABEL": "Numero circondari/distretti",
            "NOTE": "Note non presenti",
            "LINK": "",
            "GUIDA": "Numero di circondari o distretti per ripartizione geografica",
            "FORMATMASK": "999G999G999G999G999G999G990",
            "FONTE": "Istat",
            "TYPE": "NUMBER"
        },

tengo per verifica
        {
            "COLNAME": "N_COM",
            "LABEL": "Numero comuni",
            "NOTE": "Note non presenti",
            "LINK": "",
            "GUIDA": "Numero di comuni per ripartizione geografica",
            "FORMATMASK": "999G999G999G999G999G999G990",
            "FONTE": "Istat",
            "TYPE": "NUMBER"
        }
    ]
}

In [2]:
# =============================================================
# =============================================================
#
# librerie di base
import numpy as np
import pandas as pd

In [ ]:
# =============================================================
# =============================================================
#
# importo le funzioni personali per uso comune
import Moduli.Modulo_Common as pd_common

In [8]:
df_ripartizioneGeografica = pd.read_csv( pd_common.GetFolderDati()+ "//Dati_RipartizioneGeografica_All.csv")

In [9]:
df_ripartizioneGeografica.head(5)

   Unnamed: 0  COD_RIP     DEN_RIP  N_COMP  N_PROV  N_CIR_DIS  N_COM
0           0        1  Nord-ovest       2      13         53   4064
1           1        2    Nord-est       3       9         25    364
2           2        3      Centro       3      12         26    707
3           3        4         Sud       1      16         56   1855
4           4        5       Isole       2       9         33    730

In [10]:
df_ripartizioneGeografica.columns

Index(['Unnamed: 0', 'COD_RIP', 'DEN_RIP', 'N_COMP', 'N_PROV', 'N_CIR_DIS',
       'N_COM'],
      dtype='str')

In [15]:
df_ripartizioneGeografica_EDA = df_ripartizioneGeografica.copy()

In [16]:
df_ripartizioneGeografica_EDA.head(2)

   Unnamed: 0  COD_RIP     DEN_RIP  N_COMP  N_PROV  N_CIR_DIS  N_COM
0           0        1  Nord-ovest       2      13         53   4064
1           1        2    Nord-est       3       9         25    364

In [18]:
# come indicato nella prima sezione, mi tengo le colonne di interesse
df_ripartizioneGeografica_EDA = df_ripartizioneGeografica_EDA[['COD_RIP', 'DEN_RIP' ]]

In [20]:
df_ripartizioneGeografica_EDA.info()

<class 'pandas.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 2 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   COD_RIP  5 non-null      int64
 1   DEN_RIP  5 non-null      str
dtypes: int64(1), str(1)
memory usage: 212.0 bytes

In [ ]:
# a) tipo dato corretto
# b) non sono presenti colonne nulle

In [21]:
#SALVO IL DATASET FINALE

pd_common.SalvaDataset(df_ripartizioneGeografica_EDA, f"ElencoRipartizioniGeografiche",False)

      path completo file:  c:\progetto_dataanalyst\progettofinale\Analisi/ElencoRipartizioniGeografiche.csv
      Il file 'c:\progetto_dataanalyst\progettofinale\Analisi/ElencoRipartizioniGeografiche.csv' non esiste
      Il file salvato c:\progetto_dataanalyst\progettofinale\Analisi/ElencoRipartizioniGeografiche.csv