In [1]:
import pandas as pd
import numpy as np

In [2]:
# =============================================================
# =============================================================
#
# importo le funzioni personali per uso comune

#aggiunto quando ho spostato i file in una cartella a parte
import sys
sys.path.append("./Moduli")

import Moduli.Modulo_Common as pd_common

In [3]:
# =============================================================
# =============================================================
#
# importo le funzioni personali creati per questa fase


import Moduli.Modulo_Configurazione as pd_config

In [7]:
#scelta di fare il calendario da codice per imparare ad usare python
# infatti per fare il codice ho impegato tanto tempo
datainizio=f'{str(pd_config.GetAnnoInizioAnalisi())}-01-01'
datafine=f'{str(pd_config.GetAnnoInizioAnalisi() + pd_config.GetNrAnniAnalisi())}-12-31'

print(f'datainizio: {datainizio} - datafine: {datafine}' )
#crea un dataframe con 1 colonna con il range di date da a
dfcalendario = pd.DataFrame({"Data": pd.date_range(datainizio, datafine)})

datainizio: 2015-01-01 - datafine: 2026-12-31

In [8]:
#aggiungo colonna indice
dfcalendario = dfcalendario.reset_index()

In [9]:
dfcalendario.head(5)

   index       Data
0      0 2015-01-01
1      1 2015-01-02
2      2 2015-01-03
3      3 2015-01-04
4      4 2015-01-05

In [ ]:
#aggiungo le colonne legate al tempo per le analisi e filtri
dfcalendario["Anno"] = dfcalendario.Data.dt.year
dfcalendario["Mese"] = dfcalendario.Data.dt.month
dfcalendario["Giorno"] = dfcalendario.Data.dt.day
#dfcalendario["GG_name"] = dfcalendario.Data.dt.day_name
#0/1/2
# get the day of the week (Note: Monday is coded as 0, and Sunday as 6)
dfcalendario["GGSettimana"] = dfcalendario.Data.dt.day_of_week #STESSO VALORE DI dfcalendario.Data.dt.weekday
#il nome del giorno della settimana
dfcalendario["GGSettimanaDsc"] = "LUN"


#non va dfcalendario["MeseDesc"] = dfcalendario.Data.dt.month_name
dfcalendario["GGDelMese"] = dfcalendario.Data.dt.days_in_month

In [11]:
#aggiorna il datase --> fa schivo ma si migliora quando si ha tempo
def AssegnaGiorno(giornoSettimana:int,nomeDelGiorno:str):
  MASCHERA_DATI = dfcalendario["GGSettimana"]==giornoSettimana
  dfcalendario.loc[MASCHERA_DATI,"GGSettimanaDsc"]=nomeDelGiorno

In [15]:
dfcalendario[(dfcalendario.Anno==2026) &
              (dfcalendario.Mese==5) &
              (dfcalendario.Giorno==13)]

,index,Data,Anno,Mese,Giorno,GGSettimana,GGSettimanaDsc,GGDelMese
4150,4150,2026-05-13,2026,5,13,2,LUN,31

In [16]:
AssegnaGiorno(1,"MAR")
AssegnaGiorno(2,"MER")
AssegnaGiorno(3,"GIO")
AssegnaGiorno(4,"VEN")
AssegnaGiorno(5,"SAB")
AssegnaGiorno(6,"DOM")

In [17]:
dfcalendario[(dfcalendario.Anno==2026) &
              (dfcalendario.Mese==5) &
              (dfcalendario.Giorno==13)]

,index,Data,Anno,Mese,Giorno,GGSettimana,GGSettimanaDsc,GGDelMese
4150,4150,2026-05-13,2026,5,13,2,MER,31

In [19]:
dfcalendario[(dfcalendario.Anno==2026) &
              (dfcalendario.Mese==5) &
              (dfcalendario.Giorno==12)]

,index,Data,Anno,Mese,Giorno,GGSettimana,GGSettimanaDsc,GGDelMese
4149,4149,2026-05-12,2026,5,12,1,MAR,31

In [20]:
dfcalendario.info()

<class 'pandas.DataFrame'>
RangeIndex: 4383 entries, 0 to 4382
Data columns (total 8 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   index           4383 non-null   int64
 1   Data            4383 non-null   datetime64[us]
 2   Anno            4383 non-null   int32
 3   Mese            4383 non-null   int32
 4   Giorno          4383 non-null   int32
 5   GGSettimana     4383 non-null   int32
 6   GGSettimanaDsc  4383 non-null   str
 7   GGDelMese       4383 non-null   int32
dtypes: datetime64[us](1), int32(5), int64(1), str(1)
memory usage: 188.5 KB

In [21]:
#GESTIONE STAGIONE DELL'ANNO
dfcalendario["Stagione"]="Primavera"
def AssegnaStagione(mese:int,stagione:str):
  MASCHERA_DATI = dfcalendario["Mese"]==mese
  dfcalendario.loc[MASCHERA_DATI,"Stagione"]=stagione

In [22]:
AssegnaStagione(6,'Estate')#: giugno, luglio, agosto.
AssegnaStagione(7,'Estate')#: giugno, luglio, agosto.
AssegnaStagione(8,'Estate')#: giugno, luglio, agosto.

AssegnaStagione(9,'Autunno')#: Autunno: settembre, ottobre, novembre
AssegnaStagione(10,'Autunno')#:
AssegnaStagione(11,'Autunno')#:

AssegnaStagione(12,'Inverno')#:Inverno: dicembre, gennaio, febbraio
AssegnaStagione(1,'Inverno')#:Inverno: dicembre, gennaio, febbraio
AssegnaStagione(2,'Inverno')#:Inverno: dicembre, gennaio, febbraio

In [23]:
dfcalendario.sample(5)

,index,Data,Anno,Mese,Giorno,GGSettimana,GGSettimanaDsc,GGDelMese,Stagione
438,438,2016-03-14,2016,3,14,0,LUN,31,Primavera
3785,3785,2025-05-13,2025,5,13,1,MAR,31,Primavera
477,477,2016-04-22,2016,4,22,4,VEN,30,Primavera
766,766,2017-02-05,2017,2,5,6,DOM,28,Inverno
4258,4258,2026-08-29,2026,8,29,5,SAB,31,Estate

In [24]:
dfcalendario.info()

<class 'pandas.DataFrame'>
RangeIndex: 4383 entries, 0 to 4382
Data columns (total 9 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   index           4383 non-null   int64
 1   Data            4383 non-null   datetime64[us]
 2   Anno            4383 non-null   int32
 3   Mese            4383 non-null   int32
 4   Giorno          4383 non-null   int32
 5   GGSettimana     4383 non-null   int32
 6   GGSettimanaDsc  4383 non-null   str
 7   GGDelMese       4383 non-null   int32
 8   Stagione        4383 non-null   str
dtypes: datetime64[us](1), int32(5), int64(1), str(2)
memory usage: 222.7 KB

In [25]:
#voglio distingure il weekend (SAB-DOM) dagli altri gg
dfcalendario['FlgWeekend'] = False

In [26]:
#solo per sab e dom assegno il true
dfcalendario.loc[ (dfcalendario["GGSettimana"]==5) | (dfcalendario["GGSettimana"]==6),
                 'FlgWeekend'] = True

In [27]:
dfcalendario.sample(5)

,index,Data,Anno,Mese,Giorno,GGSettimana,GGSettimanaDsc,GGDelMese,Stagione,FlgWeekend
595,595,2016-08-18,2016,8,18,3,GIO,31,Estate,False
1070,1070,2017-12-06,2017,12,6,2,MER,31,Inverno,False
1864,1864,2020-02-08,2020,2,8,5,SAB,29,Inverno,True
2958,2958,2023-02-06,2023,2,6,0,LUN,28,Inverno,False
128,128,2015-05-09,2015,5,9,5,SAB,31,Primavera,True

In [28]:
#SALVO IL DATASET FINALE

pd_common.SalvaDataset(dfcalendario, f"Calendario",False)

      path completo file:  c:\progetto_dataanalyst\progettofinale\Analisi/Calendario.csv
      Il file 'c:\progetto_dataanalyst\progettofinale\Analisi/Calendario.csv' non esiste
      Il file salvato c:\progetto_dataanalyst\progettofinale\Analisi/Calendario.csv