# metadati
url: https://situas-servizi.istat.it/publish/anagrafica_report_metadato_web?pfun=73&pdata=01/01/2015

In [2]:
# =============================================================
# =============================================================
#
# librerie di base
import numpy as np
import pandas as pd
import os

In [3]:
#recupero path dedicata ai dati
def GetFolderDati():
    folderdati = os.getcwd() 
    folderdati =folderdati+ "\\Data\\" 
    return folderdati

In [4]:
df_comuni = pd.read_csv( GetFolderDati()+ "Dati_Comune_All.csv")

In [5]:
df_comuni.head(5)

,Unnamed: 0.1,Unnamed: 0,COD_RIP,COD_REG,COD_UTS,COD_PROV_STORICO,PRO_COM_T,PRO_COM,COMUNE,COMUNE_A,...,DEGURBA_2021,COD_ECO_DIV_2018,DEN_ECO_DIV_2018,COD_ECO_PRO_2018,DEN_ECO_PRO_2018,COD_ECO_SEZ_2018,DEN_ECO_SEZ_2018,COD_ECO_SSEZ_2018,DEN_ECO_SSEZ_2018,anno_riferimento
0,0,0,1,1,201,1,1001,1001,Agliè,NaN,...,3,1,Divisione Temperata,1B,Provincia Padana,1B1,Sezione Padana,1B1c,Sottosezione Bacino Occidentale del Po,2015
1,1,1,1,1,201,1,1002,1002,Airasca,NaN,...,3,1,Divisione Temperata,1B,Provincia Padana,1B1,Sezione Padana,1B1c,Sottosezione Bacino Occidentale del Po,2015
2,2,2,1,1,201,1,1003,1003,Ala di Stura,NaN,...,3,1,Divisione Temperata,1A,Provincia Alpina,1A1,Sezione Alpina Occidentale,1A1b,Sottosezione Alpi Nord-Occidentali,2015
3,3,3,1,1,201,1,1004,1004,Albiano d'Ivrea,NaN,...,3,1,Divisione Temperata,1A,Provincia Alpina,1A1,Sezione Alpina Occidentale,1A1b,Sottosezione Alpi Nord-Occidentali,2015
4,4,4,1,1,201,1,1006,1006,Almese,NaN,...,2,1,Divisione Temperata,1A,Provincia Alpina,1A1,Sezione Alpina Occidentale,1A1b,Sottosezione Alpi Nord-Occidentali,2015

In [6]:
df_comuni.columns

Index(['Unnamed: 0.1', 'Unnamed: 0', 'COD_RIP', 'COD_REG', 'COD_UTS',
       'COD_PROV_STORICO', 'PRO_COM_T', 'PRO_COM', 'COMUNE', 'COMUNE_A',
       'SIGLA_AUTOMOBILISTICA', 'COM_ISO', 'COM_LIT', 'ZONA_ALT', 'ALT',
       'ZONE_COST_2021', 'DEGURBA_2021', 'COD_ECO_DIV_2018',
       'DEN_ECO_DIV_2018', 'COD_ECO_PRO_2018', 'DEN_ECO_PRO_2018',
       'COD_ECO_SEZ_2018', 'DEN_ECO_SEZ_2018', 'COD_ECO_SSEZ_2018',
       'DEN_ECO_SSEZ_2018', 'anno_riferimento'],
      dtype='str')

In [7]:
df_comuni_EDA = df_comuni.copy()

In [8]:
df_comuni_EDA.head(2)

,Unnamed: 0.1,Unnamed: 0,COD_RIP,COD_REG,COD_UTS,COD_PROV_STORICO,PRO_COM_T,PRO_COM,COMUNE,COMUNE_A,...,DEGURBA_2021,COD_ECO_DIV_2018,DEN_ECO_DIV_2018,COD_ECO_PRO_2018,DEN_ECO_PRO_2018,COD_ECO_SEZ_2018,DEN_ECO_SEZ_2018,COD_ECO_SSEZ_2018,DEN_ECO_SSEZ_2018,anno_riferimento
0,0,0,1,1,201,1,1001,1001,Agliè,NaN,...,3,1,Divisione Temperata,1B,Provincia Padana,1B1,Sezione Padana,1B1c,Sottosezione Bacino Occidentale del Po,2015
1,1,1,1,1,201,1,1002,1002,Airasca,NaN,...,3,1,Divisione Temperata,1B,Provincia Padana,1B1,Sezione Padana,1B1c,Sottosezione Bacino Occidentale del Po,2015

#Colonne di interesse:

        {
            "COLNAME": "COD_UTS",
            "LABEL": "Codice Provincia/Uts",
            "NOTE": "Codice di tre caratteri alfanumerici con validità nell’intervallo 001-119 per le Province. AI Liberi consorzi restano assegnati i codici delle omonime ex Province (validi nell'intervallo 081-089). Il codice delle Città metropolitane è, invece, creato sommando '200' al codice dell'ex provincia di origine. Infine ai soli fini statistici, permangono i codici delle soppresse Province del Friuli-Venezia Giulia, cessate secondo le modalità espresse con L.r. 20/2016.",
            "LINK": "",
            "GUIDA": "Codice Istat della Provincia o Unità territoriale sovracomunale (Uts). Le Unità territoriali sovracomunali, definite a fini statistici, ricomprendono dal 2015 oltre alle Province anche le Città metropolitane, i Liberi consorzi e le unità non amministrative (ex Province del Friuli-Venezia Giulia), al fine di costituire una suddivisione completa del territorio nazionale.",
            "FORMATMASK": "",
            "FONTE": "Istat",
            "TYPE": "VARCHAR"
        },

        {
            "COLNAME": "COMUNE",
            "LABEL": "Comune",
            "NOTE": "La denominazione ufficiale dei comuni della Provincia di Bolzano/Bozen e di alcuni comuni del Friuli-Venezia Giulia è definita dall'associazione del nome italiano a quello straniero. Per le denominazioni bilingue è previsto l'uso del simbolo separatore: \"/\" per i comuni della Provincia di Bolzano/Bozen, e \"-\" per tutti gli altri.",
            "LINK": "",
            "GUIDA": "Denominazione del Comune in lingua italiana e straniera",
            "FORMATMASK": "",
            "FONTE": "Istat",
            "TYPE": "VARCHAR"
        },

        {
            "COLNAME": "PRO_COM",
            "LABEL": "Codice comune (numerico)",
            "NOTE": "Note non presenti",
            "LINK": "",
            "GUIDA": "Codice Istat del Comune di sei caratteri in formato numerico",
            "FORMATMASK": "",
            "FONTE": "Istat",
            "TYPE": "NUMBER"
        },

        {
            "COLNAME": "COD_REG",
            "LABEL": "Codice Regione",
            "NOTE": "Valore  di due caratteri alfanumerici, con validità nell'intervallo  01- 20.",
            "LINK": "",
            "GUIDA": "Codice Istat della Regione",
            "FORMATMASK": "",
            "FONTE": "Istat",
            "TYPE": "VARCHAR"
        },

         {
            "COLNAME": "COD_RIP",
            "LABEL": "Codice Ripartizione geografica",
            "NOTE": "Note non presenti",
            "LINK": "",
            "GUIDA": "Codice Istat della ripartizione geografica secondo la suddivisione del territorio nazionale in: 1) Nord-ovest, 2) Nord-est, 3) Centro, 4) Sud e 5) Isole.",
            "FORMATMASK": "",
            "FONTE": "Istat",
            "TYPE": "NUMBER"
        },

In [22]:
df_comuni_EDA = df_comuni_EDA[['COD_RIP', 'COD_REG', 'COD_UTS',
       'PRO_COM', 'COMUNE']]

In [23]:
df_comuni_EDA['COD_RIP'].unique()

array([1, 2, 3, 4, 5])

In [24]:
df_comuni_EDA[df_comuni_EDA['COD_RIP']==1].head(5)

   COD_RIP  COD_REG  COD_UTS  PRO_COM           COMUNE
0        1        1      201     1001            Agliè
1        1        1      201     1002          Airasca
2        1        1      201     1003     Ala di Stura
3        1        1      201     1004  Albiano d'Ivrea
4        1        1      201     1006           Almese

In [ ]:
df_comuni_EDA['COD_REG'].unique()

array([0, 1])

In [20]:
df_comuni_EDA['ZONA_ALT'].unique()

array([3, 5, 1, 4, 2])