In [101]:
import numpy as np
import pandas as pd

In [102]:
# =============================================================
# =============================================================
#
# importo le funzioni personali creati per questa fase


#aggiunto quando ho spostato i file in una cartella a parte
import sys
sys.path.append("./Moduli")

import Moduli.Modulo_Common as pd_common

In [103]:
df_incidenti_an = pd.read_csv( pd_common.GetFolderAnalisi()+ "//ElencoIncidenti.csv")

In [104]:
df_incidenti_an.TIME_PERIOD.unique()

array([2010, 2011, 2012, 2013, 2014, 2015, 2016, 2018, 2019, 2020, 2021,
       2022, 2023, 2024, 2017])

In [105]:
df_comuni_an = pd.read_csv( pd_common.GetFolderAnalisi()+ "//ElencoComuni.csv")

In [106]:
df_comuni_an.anno_riferimento.unique()

array([2010, 2011, 2012, 2013, 2014, 2015, 2016, 2017, 2018, 2019, 2020,
       2021, 2022, 2023, 2024, 2025, 2026])

In [107]:
df_province_an = pd.read_csv( pd_common.GetFolderAnalisi()+ "//ElencoProvince.csv")

In [108]:
df_province_an.anno_riferimento.unique()

array([2010, 2011, 2012, 2013, 2014, 2015, 2016, 2017, 2018, 2019, 2020,
       2021, 2022, 2023, 2024, 2025, 2026])

In [109]:
df_regioni_an = pd.read_csv( pd_common.GetFolderAnalisi()+ "//ElencoRegioni.csv")

In [110]:
df_regioni_an.anno_riferimento.unique()

array([2010, 2011, 2012, 2013, 2014, 2015, 2016, 2017, 2018, 2019, 2020,
       2021, 2022, 2023, 2024, 2025, 2026])

In [111]:
df_ripgeo_an = pd.read_csv( pd_common.GetFolderAnalisi()+ "//ElencoRipartizioniGeografiche.csv")

In [112]:
df_calendario = pd.read_csv( pd_common.GetFolderAnalisi()+ "//Calendario.csv")

In [113]:
df_regioni_an.columns

Index(['Unnamed: 0', 'anno_riferimento', 'COD_RIP', 'COD_REG', 'DEN_REG'], dtype='object')

In [114]:
df_regioni_an.COD_REG.count()

np.int64(340)

In [115]:
df_ripgeo_an.columns

Index(['Unnamed: 0', 'COD_RIP', 'DEN_RIP'], dtype='object')

In [116]:
df_ripgeo_an.COD_RIP.count()

np.int64(5)

In [117]:
#merge tra regioni e ripartizione geografica
# la chiave di relazione è COD_RIP per ambedue le tb
df_reg_ripgeo_merge = df_regioni_an.merge(df_ripgeo_an[['COD_RIP','DEN_RIP']],
                                            how='inner', 
                                            left_on='COD_RIP', 
                                            right_on='COD_RIP')

In [118]:
df_reg_ripgeo_merge.columns

Index(['Unnamed: 0', 'anno_riferimento', 'COD_RIP', 'COD_REG', 'DEN_REG',
       'DEN_RIP'],
      dtype='object')

In [119]:
df_reg_ripgeo_merge.head(3)

,Unnamed: 0,anno_riferimento,COD_RIP,COD_REG,DEN_REG,DEN_RIP
0,0,2010,1,1,Piemonte,Nord-ovest
1,1,2010,1,2,Valle d'Aosta/Vallée d'Aoste,Nord-ovest
2,2,2010,1,3,Lombardia,Nord-ovest

In [120]:
nr_rec_reg = df_regioni_an.COD_REG.count()
nr_rec_merge_reg = df_reg_ripgeo_merge.COD_REG.count()
print(f'Sorgente: {nr_rec_reg} - Mege: {nr_rec_merge_reg}')

Sorgente: 340 - Mege: 340

In [121]:
df_province_an.columns

Index(['Unnamed: 0', 'anno_riferimento', 'COD_REG', 'COD_UTS', 'DEN_UTS'], dtype='object')

In [122]:
df_province_an.COD_UTS.count()

np.int64(1843)

In [123]:
df_province_an.groupby(['anno_riferimento'])['anno_riferimento'].agg('count')

anno_riferimento
2010    110
2011    110
2012    110
2013    110
2014    110
2015    110
2016    110
2017    107
2018    107
2019    107
2020    107
2021    107
2022    107
2023    107
2024    107
2025    107
2026    110
Name: anno_riferimento, dtype: int64

In [124]:
#merge tra province e regioni-ripartizione geografica
# la chiave di relazione è anno_riferimento e COD_REG per ambedue le tb
df_prov_reg_ripgeo_merge = df_province_an.merge(df_reg_ripgeo_merge[['anno_riferimento', 'COD_RIP', 'COD_REG', 'DEN_REG',
                                                                'DEN_RIP']],
                                            how='inner', 
                                            left_on=['anno_riferimento','COD_REG'], 
                                            right_on=['anno_riferimento','COD_REG'])

In [125]:
df_prov_reg_ripgeo_merge.groupby(['anno_riferimento'])['anno_riferimento'].agg('count')

anno_riferimento
2010    110
2011    110
2012    110
2013    110
2014    110
2015    110
2016    110
2017    107
2018    107
2019    107
2020    107
2021    107
2022    107
2023    107
2024    107
2025    107
2026    110
Name: anno_riferimento, dtype: int64

In [126]:
df_prov_reg_ripgeo_merge.columns

Index(['Unnamed: 0', 'anno_riferimento', 'COD_REG', 'COD_UTS', 'DEN_UTS',
       'COD_RIP', 'DEN_REG', 'DEN_RIP'],
      dtype='object')

In [127]:
#riordino elementi
df_prov_reg_ripgeo_merge = df_prov_reg_ripgeo_merge[[ 'anno_riferimento','COD_RIP', 'DEN_RIP', 'COD_REG', 'DEN_REG', 'COD_UTS', 'DEN_UTS']]

In [128]:
df_prov_reg_ripgeo_merge.columns

Index(['anno_riferimento', 'COD_RIP', 'DEN_RIP', 'COD_REG', 'DEN_REG',
       'COD_UTS', 'DEN_UTS'],
      dtype='object')

In [129]:
df_prov_reg_ripgeo_merge.head(5)

   anno_riferimento  COD_RIP     DEN_RIP  COD_REG   DEN_REG  COD_UTS   DEN_UTS
0              2010        1  Nord-ovest        1  Piemonte        1    Torino
1              2010        1  Nord-ovest        1  Piemonte        2  Vercelli
2              2010        1  Nord-ovest        1  Piemonte        3    Novara
3              2010        1  Nord-ovest        1  Piemonte        4     Cuneo
4              2010        1  Nord-ovest        1  Piemonte        5      Asti

In [130]:
nr_rec_prov = df_province_an.COD_UTS.count()
nr_rec_merge_prov = df_prov_reg_ripgeo_merge.COD_UTS.count()
print(f'Sorgente: {nr_rec_prov} - Mege: {nr_rec_merge_prov}')

Sorgente: 1843 - Mege: 1843

In [131]:
df_comuni_an.columns

Index(['Unnamed: 0', 'anno_riferimento', 'COD_UTS', 'PRO_COM', 'COMUNE',
       'AREA_KMQ', 'POP_RES'],
      dtype='object')

In [132]:
#merge tra comuni e regioni-ripartizione geografica
# la chiave di relazione è anno_riferimento e COD_UPS per ambedue le tb
df_com_prov_reg_geo_merge = df_comuni_an.merge(df_prov_reg_ripgeo_merge[['anno_riferimento','COD_RIP', 'DEN_RIP', 'COD_REG', 'DEN_REG',
       'COD_UTS', 'DEN_UTS']],
                                            how='inner', 
                                            left_on=['anno_riferimento','COD_UTS'], 
                                            right_on=['anno_riferimento','COD_UTS'])

In [133]:
df_com_prov_reg_geo_merge.columns

Index(['Unnamed: 0', 'anno_riferimento', 'COD_UTS', 'PRO_COM', 'COMUNE',
       'AREA_KMQ', 'POP_RES', 'COD_RIP', 'DEN_RIP', 'COD_REG', 'DEN_REG',
       'DEN_UTS'],
      dtype='object')

In [134]:
df_com_prov_reg_geo_merge.anno_riferimento.unique()

array([2010, 2011, 2012, 2013, 2014, 2015, 2016, 2017, 2018, 2019, 2020,
       2021, 2022, 2023, 2024, 2025, 2026])

In [135]:
nr_rec_com = df_comuni_an.PRO_COM.count()
nr_rec_merge_com = df_com_prov_reg_geo_merge.PRO_COM.count()
print(f'Sorgente: {nr_rec_com} - Mege: {nr_rec_merge_com}')

Sorgente: 135649 - Mege: 135649

In [136]:
#RIORDINO LE COLONNE
df_com_prov_reg_geo_merge= df_com_prov_reg_geo_merge[ [
 'anno_riferimento', 
        'COD_RIP', 'DEN_RIP', 'COD_REG', 'DEN_REG',
       'COD_UTS', 'DEN_UTS','PRO_COM', 'COMUNE','AREA_KMQ', 'POP_RES']]

In [137]:
#mi servono i decimali per rendere univoca la densità
df_com_prov_reg_geo_merge['POP_AL_KMQ'] = round(df_com_prov_reg_geo_merge['POP_RES'] / df_com_prov_reg_geo_merge['AREA_KMQ'] ,6)

In [138]:
#definisco una colonna densità che accorpa 2 informazioni
df_com_prov_reg_geo_merge['POP_AL_KMQ']

0         199.449271
1         240.544370
2           9.863700
3         147.808446
4          96.346685
             ...
135644    119.182605
135645     31.674865
135646     36.088165
135647     27.863106
135648     12.951073
Name: POP_AL_KMQ, Length: 135649, dtype: float64

In [139]:
#verifico univocità densità sui comuni. prendo 2026 che si prende per il previsionale/forecast
df_ver_com_den26 = df_com_prov_reg_geo_merge[df_com_prov_reg_geo_merge['anno_riferimento']==2026].groupby(['PRO_COM','POP_AL_KMQ'] , as_index=False).size()

In [140]:
df_ver_com_den26.shape

(7895, 3)

In [141]:
df_ver_com_den26.sort_values('size', ascending=False)

      PRO_COM   POP_AL_KMQ  size
0        1001   196.633273     1
5274    65010    92.019704     1
5272    65008    38.797699     1
5271    65007  2485.924957     1
5270    65006   806.762101     1
...       ...          ...   ...
2627    20057   230.735945     1
2626    20056    93.066630     1
2625    20055    96.210213     1
2624    20054   109.471425     1
7894   119024    12.951073     1

[7895 rows x 3 columns]

In [142]:
#ulteriore verifica
df_ver_com_den26[df_ver_com_den26['size']>1]

Empty DataFrame
Columns: [PRO_COM, POP_AL_KMQ, size]
Index: []

In [143]:
df_com_prov_reg_geo_merge.columns

Index(['anno_riferimento', 'COD_RIP', 'DEN_RIP', 'COD_REG', 'DEN_REG',
       'COD_UTS', 'DEN_UTS', 'PRO_COM', 'COMUNE', 'AREA_KMQ', 'POP_RES',
       'POP_AL_KMQ'],
      dtype='object')

In [144]:
df_com_prov_reg_geo_merge.anno_riferimento.unique()

array([2010, 2011, 2012, 2013, 2014, 2015, 2016, 2017, 2018, 2019, 2020,
       2021, 2022, 2023, 2024, 2025, 2026])

In [145]:
#SALVO IL DATASET FINALE

pd_common.SalvaDataset(df_com_prov_reg_geo_merge, f"ElencoComuniProvinceRegioniRipGeografiche",False)

      path completo file:  c:\progetto_dataanalyst\progettofinale\Analisi/ElencoComuniProvinceRegioniRipGeografiche.csv
         Il file 'c:\progetto_dataanalyst\progettofinale\Analisi/ElencoComuniProvinceRegioniRipGeografiche.csv' esiste, per cui lo rimuovo
      Il file salvato c:\progetto_dataanalyst\progettofinale\Analisi/ElencoComuniProvinceRegioniRipGeografiche.csv

In [146]:
df_incidenti_an.columns

Index(['Unnamed: 0.1', 'Unnamed: 0', 'REF_AREA', 'RESULT', 'TIME_PERIOD',
       'OBS_VALUE', 'RESULT_DESC'],
      dtype='object')

In [147]:
df_com_prov_reg_geo_merge.columns

Index(['anno_riferimento', 'COD_RIP', 'DEN_RIP', 'COD_REG', 'DEN_REG',
       'COD_UTS', 'DEN_UTS', 'PRO_COM', 'COMUNE', 'AREA_KMQ', 'POP_RES',
       'POP_AL_KMQ'],
      dtype='object')

In [148]:
df_incidenti_an.TIME_PERIOD.unique()

array([2010, 2011, 2012, 2013, 2014, 2015, 2016, 2018, 2019, 2020, 2021,
       2022, 2023, 2024, 2017])

In [149]:
#merge tra comuni e regioni-ripartizione geografica
# la chiave di relazione è COD_REG per ambedue le tb
#df_incidente_flat = 
df_incidenti_flat_an= df_incidenti_an.merge(df_com_prov_reg_geo_merge[['anno_riferimento',
                                                'COD_RIP', 'DEN_RIP', 
                                                'COD_REG', 'DEN_REG',
                                                'COD_UTS', 'DEN_UTS', 
                                                'PRO_COM', 'COMUNE', 'AREA_KMQ', 'POP_RES',
                                                'POP_AL_KMQ']],
                                            how='inner', 
                                            left_on=['TIME_PERIOD','REF_AREA'], 
                                            right_on=['anno_riferimento','PRO_COM'])

In [150]:
df_incidenti_flat_an.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 118111 entries, 0 to 118110
Data columns (total 19 columns):
 #   Column            Non-Null Count   Dtype
---  ------            --------------   -----
 0   Unnamed: 0.1      118111 non-null  int64
 1   Unnamed: 0        118111 non-null  int64
 2   REF_AREA          118111 non-null  int64
 3   RESULT            118111 non-null  object
 4   TIME_PERIOD       118111 non-null  int64
 5   OBS_VALUE         118111 non-null  int64
 6   RESULT_DESC       118111 non-null  object
 7   anno_riferimento  118111 non-null  int64
 8   COD_RIP           118111 non-null  int64
 9   DEN_RIP           118111 non-null  object
 10  COD_REG           118111 non-null  int64
 11  DEN_REG           118111 non-null  object
 12  COD_UTS           118111 non-null  int64
 13  DEN_UTS           118111 non-null  object
 14  PRO_COM           118111 non-null  int64
 15  COMUNE            118111 non-null  object
 16  AREA_KMQ          118111 non-null  float64
 17  POP_RES           118111 non-null  int64
 18  POP_AL_KMQ        118111 non-null  float64
dtypes: float64(2), int64(11), object(6)
memory usage: 17.1+ MB

In [151]:
df_incidenti_flat_an[
    df_incidenti_flat_an['anno_riferimento']==df_incidenti_flat_an['TIME_PERIOD']
    ].count()

Unnamed: 0.1        118111
Unnamed: 0          118111
REF_AREA            118111
RESULT              118111
TIME_PERIOD         118111
OBS_VALUE           118111
RESULT_DESC         118111
anno_riferimento    118111
COD_RIP             118111
DEN_RIP             118111
COD_REG             118111
DEN_REG             118111
COD_UTS             118111
DEN_UTS             118111
PRO_COM             118111
COMUNE              118111
AREA_KMQ            118111
POP_RES             118111
POP_AL_KMQ          118111
dtype: int64

In [152]:
df_incidenti_flat_an[
    df_incidenti_flat_an['anno_riferimento']!=df_incidenti_flat_an['TIME_PERIOD']
    ].count()

Unnamed: 0.1        0
Unnamed: 0          0
REF_AREA            0
RESULT              0
TIME_PERIOD         0
OBS_VALUE           0
RESULT_DESC         0
anno_riferimento    0
COD_RIP             0
DEN_RIP             0
COD_REG             0
DEN_REG             0
COD_UTS             0
DEN_UTS             0
PRO_COM             0
COMUNE              0
AREA_KMQ            0
POP_RES             0
POP_AL_KMQ          0
dtype: int64

In [153]:
df_incidenti_flat_an = df_incidenti_flat_an.drop('anno_riferimento', axis=1)

In [154]:
df_incidenti_flat_an[
    df_incidenti_flat_an['REF_AREA']==df_incidenti_flat_an['PRO_COM']
    ].count()

Unnamed: 0.1    118111
Unnamed: 0      118111
REF_AREA        118111
RESULT          118111
TIME_PERIOD     118111
OBS_VALUE       118111
RESULT_DESC     118111
COD_RIP         118111
DEN_RIP         118111
COD_REG         118111
DEN_REG         118111
COD_UTS         118111
DEN_UTS         118111
PRO_COM         118111
COMUNE          118111
AREA_KMQ        118111
POP_RES         118111
POP_AL_KMQ      118111
dtype: int64

In [155]:
df_incidenti_flat_an[
    df_incidenti_flat_an['REF_AREA']!=df_incidenti_flat_an['PRO_COM']
    ].count()

Unnamed: 0.1    0
Unnamed: 0      0
REF_AREA        0
RESULT          0
TIME_PERIOD     0
OBS_VALUE       0
RESULT_DESC     0
COD_RIP         0
DEN_RIP         0
COD_REG         0
DEN_REG         0
COD_UTS         0
DEN_UTS         0
PRO_COM         0
COMUNE          0
AREA_KMQ        0
POP_RES         0
POP_AL_KMQ      0
dtype: int64

In [156]:
df_incidenti_flat_an = df_incidenti_flat_an.drop('REF_AREA', axis=1)

In [157]:
df_incidenti_flat_an.columns

Index(['Unnamed: 0.1', 'Unnamed: 0', 'RESULT', 'TIME_PERIOD', 'OBS_VALUE',
       'RESULT_DESC', 'COD_RIP', 'DEN_RIP', 'COD_REG', 'DEN_REG', 'COD_UTS',
       'DEN_UTS', 'PRO_COM', 'COMUNE', 'AREA_KMQ', 'POP_RES', 'POP_AL_KMQ'],
      dtype='object')

In [158]:
#riprdino le colonne
df_incidenti_flat_an = df_incidenti_flat_an[[ 'TIME_PERIOD', 
        'COD_RIP', 'DEN_RIP', 'COD_REG', 'DEN_REG', 'COD_UTS',
       'DEN_UTS', 'PRO_COM', 'COMUNE', 'AREA_KMQ', 'POP_RES', 'POP_AL_KMQ','RESULT','RESULT_DESC','OBS_VALUE']]

In [159]:
df_incidenti_flat_an = df_incidenti_flat_an.reset_index()

In [160]:
df_incidenti_flat_an.head(5)

,index,TIME_PERIOD,COD_RIP,DEN_RIP,COD_REG,DEN_REG,COD_UTS,DEN_UTS,PRO_COM,COMUNE,AREA_KMQ,POP_RES,POP_AL_KMQ,RESULT,RESULT_DESC,OBS_VALUE
0,0,2010,1,Nord-ovest,1,Piemonte,1,Torino,1001,Agliè,13.1462,2622,199.449271,F,Feriti,14
1,1,2011,1,Nord-ovest,1,Piemonte,1,Torino,1001,Agliè,13.1462,2615,198.916797,F,Feriti,6
2,2,2012,1,Nord-ovest,1,Piemonte,1,Torino,1001,Agliè,13.1462,2657,202.111637,F,Feriti,8
3,3,2013,1,Nord-ovest,1,Piemonte,1,Torino,1001,Agliè,13.1462,2722,207.056031,F,Feriti,5
4,4,2014,1,Nord-ovest,1,Piemonte,1,Torino,1001,Agliè,13.1462,2748,209.033789,F,Feriti,11

In [161]:
df_incidenti_flat_an.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 118111 entries, 0 to 118110
Data columns (total 16 columns):
 #   Column       Non-Null Count   Dtype
---  ------       --------------   -----
 0   index        118111 non-null  int64
 1   TIME_PERIOD  118111 non-null  int64
 2   COD_RIP      118111 non-null  int64
 3   DEN_RIP      118111 non-null  object
 4   COD_REG      118111 non-null  int64
 5   DEN_REG      118111 non-null  object
 6   COD_UTS      118111 non-null  int64
 7   DEN_UTS      118111 non-null  object
 8   PRO_COM      118111 non-null  int64
 9   COMUNE       118111 non-null  object
 10  AREA_KMQ     118111 non-null  float64
 11  POP_RES      118111 non-null  int64
 12  POP_AL_KMQ   118111 non-null  float64
 13  RESULT       118111 non-null  object
 14  RESULT_DESC  118111 non-null  object
 15  OBS_VALUE    118111 non-null  int64
dtypes: float64(2), int64(8), object(6)
memory usage: 14.4+ MB

In [162]:
#tutto in strin e non object
df_incidenti_flat_an['DEN_RIP'] = df_incidenti_flat_an['DEN_RIP'].astype('string')
df_incidenti_flat_an['DEN_REG'] = df_incidenti_flat_an['DEN_REG'].astype('string')
df_incidenti_flat_an['DEN_UTS'] = df_incidenti_flat_an['DEN_UTS'].astype('string')
df_incidenti_flat_an['COMUNE'] = df_incidenti_flat_an['COMUNE'].astype('string')
df_incidenti_flat_an['RESULT'] = df_incidenti_flat_an['RESULT'].astype('string')
df_incidenti_flat_an['RESULT_DESC'] = df_incidenti_flat_an['RESULT_DESC'].astype('string')

In [163]:
df_incidenti_flat_an.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 118111 entries, 0 to 118110
Data columns (total 16 columns):
 #   Column       Non-Null Count   Dtype
---  ------       --------------   -----
 0   index        118111 non-null  int64
 1   TIME_PERIOD  118111 non-null  int64
 2   COD_RIP      118111 non-null  int64
 3   DEN_RIP      118111 non-null  string
 4   COD_REG      118111 non-null  int64
 5   DEN_REG      118111 non-null  string
 6   COD_UTS      118111 non-null  int64
 7   DEN_UTS      118111 non-null  string
 8   PRO_COM      118111 non-null  int64
 9   COMUNE       118111 non-null  string
 10  AREA_KMQ     118111 non-null  float64
 11  POP_RES      118111 non-null  int64
 12  POP_AL_KMQ   118111 non-null  float64
 13  RESULT       118111 non-null  string
 14  RESULT_DESC  118111 non-null  string
 15  OBS_VALUE    118111 non-null  int64
dtypes: float64(2), int64(8), string(6)
memory usage: 14.4 MB

In [164]:
df_incidenti_flat_an.TIME_PERIOD.unique()

array([2010, 2011, 2012, 2013, 2014, 2015, 2016, 2018, 2019, 2020, 2021,
       2022, 2023, 2024, 2017])

In [165]:
#assegno l'ambito dei dati ottenuti da istat come storico
df_incidenti_flat_an['TIPO_DATO'] ='S'
df_incidenti_flat_an['TIPO_DATO_DSC'] ='Storico'

In [166]:
df_incidenti_flat_an['TIPO_DATO'] = df_incidenti_flat_an['TIPO_DATO'].astype('string')
df_incidenti_flat_an['TIPO_DATO_DSC'] = df_incidenti_flat_an['TIPO_DATO_DSC'].astype('string')

In [168]:
df_incidenti_flat_an.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 118111 entries, 0 to 118110
Data columns (total 18 columns):
 #   Column         Non-Null Count   Dtype
---  ------         --------------   -----
 0   index          118111 non-null  int64
 1   TIME_PERIOD    118111 non-null  int64
 2   COD_RIP        118111 non-null  int64
 3   DEN_RIP        118111 non-null  string
 4   COD_REG        118111 non-null  int64
 5   DEN_REG        118111 non-null  string
 6   COD_UTS        118111 non-null  int64
 7   DEN_UTS        118111 non-null  string
 8   PRO_COM        118111 non-null  int64
 9   COMUNE         118111 non-null  string
 10  AREA_KMQ       118111 non-null  float64
 11  POP_RES        118111 non-null  int64
 12  POP_AL_KMQ     118111 non-null  float64
 13  RESULT         118111 non-null  string
 14  RESULT_DESC    118111 non-null  string
 15  OBS_VALUE      118111 non-null  int64
 16  TIPO_DATO      118111 non-null  string
 17  TIPO_DATO_DSC  118111 non-null  string
dtypes: float64(2), int64(8), string(8)
memory usage: 16.2 MB

In [167]:
#SALVO IL DATASET FINALE

pd_common.SalvaDataset(df_incidenti_flat_an, f"Incidenti_flat",False)

      path completo file:  c:\progetto_dataanalyst\progettofinale\Analisi/Incidenti_flat.csv
         Il file 'c:\progetto_dataanalyst\progettofinale\Analisi/Incidenti_flat.csv' esiste, per cui lo rimuovo
      Il file salvato c:\progetto_dataanalyst\progettofinale\Analisi/Incidenti_flat.csv