In [40]:
import numpy as np
import pandas as pd

In [41]:
# =============================================================
# =============================================================
#
# importo le funzioni personali creati per questa fase


#aggiunto quando ho spostato i file in una cartella a parte
import sys
sys.path.append("./Moduli")

import Moduli.Modulo_Common as pd_common

In [42]:
df_incidenti_an = pd.read_csv( pd_common.GetFolderAnalisi()+ "//ElencoIncidenti.csv")

In [43]:
df_comuni_an = pd.read_csv( pd_common.GetFolderAnalisi()+ "//ElencoComuni.csv")

In [44]:
df_province_an = pd.read_csv( pd_common.GetFolderAnalisi()+ "//ElencoProvince.csv")

In [45]:
df_regioni_an = pd.read_csv( pd_common.GetFolderAnalisi()+ "//ElencoRegioni.csv")

In [46]:
df_ripgeo_an = pd.read_csv( pd_common.GetFolderAnalisi()+ "//ElencoRipartizioniGeografiche.csv")

In [47]:
df_calendario = pd.read_csv( pd_common.GetFolderAnalisi()+ "//Calendario.csv")

In [48]:
df_regioni_an.columns

Index(['Unnamed: 0', 'anno_riferimento', 'COD_RIP', 'COD_REG', 'DEN_REG'], dtype='str')

In [49]:
df_regioni_an.COD_REG.count()

np.int64(240)

In [50]:
df_ripgeo_an.columns

Index(['Unnamed: 0', 'COD_RIP', 'DEN_RIP'], dtype='str')

In [51]:
df_ripgeo_an.COD_RIP.count()

np.int64(5)

In [52]:
#merge tra regioni e ripartizione geografica
# la chiave di relazione è COD_RIP per ambedue le tb
df_reg_ripgeo_merge = df_regioni_an.merge(df_ripgeo_an[['COD_RIP','DEN_RIP']],
                                            how='inner', 
                                            left_on='COD_RIP', 
                                            right_on='COD_RIP')

In [53]:
df_reg_ripgeo_merge.columns

Index(['Unnamed: 0', 'anno_riferimento', 'COD_RIP', 'COD_REG', 'DEN_REG',
       'DEN_RIP'],
      dtype='str')

In [54]:
df_reg_ripgeo_merge.head(3)

,Unnamed: 0,anno_riferimento,COD_RIP,COD_REG,DEN_REG,DEN_RIP
0,0,2015,1,1,Piemonte,Nord-ovest
1,1,2015,1,2,Valle d'Aosta/Vallée d'Aoste,Nord-ovest
2,2,2015,1,3,Lombardia,Nord-ovest

In [55]:
nr_rec_reg = df_regioni_an.COD_REG.count()
nr_rec_merge_reg = df_reg_ripgeo_merge.COD_REG.count()
print(f'Sorgente: {nr_rec_reg} - Mege: {nr_rec_merge_reg}')

Sorgente: 240 - Mege: 240

In [56]:
df_province_an.columns

Index(['Unnamed: 0', 'anno_riferimento', 'COD_REG', 'COD_UTS', 'DEN_UTS'], dtype='str')

In [57]:
df_province_an.COD_UTS.count()

np.int64(1293)

In [58]:
#merge tra province e regioni-ripartizione geografica
# la chiave di relazione è anno_riferimento e COD_REG per ambedue le tb
df_prov_reg_ripgeo_merge = df_province_an.merge(df_reg_ripgeo_merge[['anno_riferimento', 'COD_RIP', 'COD_REG', 'DEN_REG',
                                                                'DEN_RIP']],
                                            how='inner', 
                                            left_on=['anno_riferimento','COD_REG'], 
                                            right_on=['anno_riferimento','COD_REG'])

In [59]:
df_prov_reg_ripgeo_merge.columns

Index(['Unnamed: 0', 'anno_riferimento', 'COD_REG', 'COD_UTS', 'DEN_UTS',
       'COD_RIP', 'DEN_REG', 'DEN_RIP'],
      dtype='str')

In [60]:
#riordino elementi
df_prov_reg_ripgeo_merge = df_prov_reg_ripgeo_merge[[ 'anno_riferimento','COD_RIP', 'DEN_RIP', 'COD_REG', 'DEN_REG', 'COD_UTS', 'DEN_UTS']]

In [61]:
df_prov_reg_ripgeo_merge.columns

Index(['anno_riferimento', 'COD_RIP', 'DEN_RIP', 'COD_REG', 'DEN_REG',
       'COD_UTS', 'DEN_UTS'],
      dtype='str')

In [62]:
df_prov_reg_ripgeo_merge.head(5)

,anno_riferimento,COD_RIP,DEN_RIP,COD_REG,DEN_REG,COD_UTS,DEN_UTS
0,2015,1,Nord-ovest,1,Piemonte,2,Vercelli
1,2015,1,Nord-ovest,1,Piemonte,3,Novara
2,2015,1,Nord-ovest,1,Piemonte,4,Cuneo
3,2015,1,Nord-ovest,1,Piemonte,5,Asti
4,2015,1,Nord-ovest,1,Piemonte,6,Alessandria

In [63]:
nr_rec_prov = df_province_an.COD_UTS.count()
nr_rec_merge_prov = df_prov_reg_ripgeo_merge.COD_UTS.count()
print(f'Sorgente: {nr_rec_prov} - Mege: {nr_rec_merge_prov}')

Sorgente: 1293 - Mege: 1293

In [64]:
df_comuni_an.columns

Index(['Unnamed: 0', 'anno_riferimento', 'COD_UTS', 'PRO_COM', 'COMUNE',
       'AREA_KMQ', 'POP_RES'],
      dtype='str')

In [65]:
#merge tra comuni e regioni-ripartizione geografica
# la chiave di relazione è anno_riferimento e COD_UPS per ambedue le tb
df_com_prov_reg_geo_merge = df_comuni_an.merge(df_prov_reg_ripgeo_merge[['anno_riferimento','COD_RIP', 'DEN_RIP', 'COD_REG', 'DEN_REG',
       'COD_UTS', 'DEN_UTS']],
                                            how='inner', 
                                            left_on=['anno_riferimento','COD_UTS'], 
                                            right_on=['anno_riferimento','COD_UTS'])

In [66]:
df_com_prov_reg_geo_merge.columns

Index(['Unnamed: 0', 'anno_riferimento', 'COD_UTS', 'PRO_COM', 'COMUNE',
       'AREA_KMQ', 'POP_RES', 'COD_RIP', 'DEN_RIP', 'COD_REG', 'DEN_REG',
       'DEN_UTS'],
      dtype='str')

In [67]:
nr_rec_com = df_comuni_an.PRO_COM.count()
nr_rec_merge_com = df_com_prov_reg_geo_merge.PRO_COM.count()
print(f'Sorgente: {nr_rec_com} - Mege: {nr_rec_merge_com}')

Sorgente: 95211 - Mege: 95211

In [68]:
#RIORDINO LE COLONNE
df_com_prov_reg_geo_merge= df_com_prov_reg_geo_merge[ [
 'anno_riferimento', 
        'COD_RIP', 'DEN_RIP', 'COD_REG', 'DEN_REG',
       'COD_UTS', 'DEN_UTS','PRO_COM', 'COMUNE','AREA_KMQ', 'POP_RES']]

In [69]:
df_com_prov_reg_geo_merge['POP_AL_KMQ'] = round(df_com_prov_reg_geo_merge['POP_RES'] / df_com_prov_reg_geo_merge['AREA_KMQ'] ,2)

In [70]:
#definisco una colonna densità che accorpa 2 informazioni
df_com_prov_reg_geo_merge['POP_AL_KMQ']

0        205.46
1        241.31
2         10.04
3        149.51
4         97.16
          ...
95206    119.18
95207     31.67
95208     36.09
95209     27.86
95210     12.95
Name: POP_AL_KMQ, Length: 95211, dtype: float64

In [71]:
df_com_prov_reg_geo_merge.columns

Index(['anno_riferimento', 'COD_RIP', 'DEN_RIP', 'COD_REG', 'DEN_REG',
       'COD_UTS', 'DEN_UTS', 'PRO_COM', 'COMUNE', 'AREA_KMQ', 'POP_RES',
       'POP_AL_KMQ'],
      dtype='str')

In [72]:
#SALVO IL DATASET FINALE

pd_common.SalvaDataset(df_com_prov_reg_geo_merge, f"ElencoComuniProvinceRegioniRipGeografiche",False)

      path completo file:  c:\progetto_dataanalyst\progettofinale\Analisi/ElencoComuniProvinceRegioniRipGeografiche.csv
         Il file 'c:\progetto_dataanalyst\progettofinale\Analisi/ElencoComuniProvinceRegioniRipGeografiche.csv' esiste, per cui lo rimuovo
      Il file salvato c:\progetto_dataanalyst\progettofinale\Analisi/ElencoComuniProvinceRegioniRipGeografiche.csv

In [73]:
df_incidenti_an.columns

Index(['Unnamed: 0.1', 'Unnamed: 0', 'REF_AREA', 'RESULT', 'TIME_PERIOD',
       'OBS_VALUE', 'RESULT_DESC'],
      dtype='str')

In [74]:
df_com_prov_reg_geo_merge.columns

Index(['anno_riferimento', 'COD_RIP', 'DEN_RIP', 'COD_REG', 'DEN_REG',
       'COD_UTS', 'DEN_UTS', 'PRO_COM', 'COMUNE', 'AREA_KMQ', 'POP_RES',
       'POP_AL_KMQ'],
      dtype='str')

In [75]:
df_incidenti_an.TIME_PERIOD.unique()

array([2001, 2002, 2003, 2004, 2005, 2006, 2007, 2008, 2009, 2010, 2011,
       2012, 2013, 2014, 2015, 2016, 2018, 2019, 2020, 2021, 2022, 2023,
       2024, 2017])

In [76]:
#merge tra comuni e regioni-ripartizione geografica
# la chiave di relazione è COD_REG per ambedue le tb
#df_incidente_flat = 
df_incidenti_flat_an= df_incidenti_an.merge(df_com_prov_reg_geo_merge[['anno_riferimento',
                                                'COD_RIP', 'DEN_RIP', 
                                                'COD_REG', 'DEN_REG',
                                                'COD_UTS', 'DEN_UTS', 
                                                'PRO_COM', 'COMUNE', 'AREA_KMQ', 'POP_RES',
                                                'POP_AL_KMQ']],
                                            how='inner', 
                                            left_on=['TIME_PERIOD','REF_AREA'], 
                                            right_on=['anno_riferimento','PRO_COM'])

In [77]:
df_incidenti_flat_an.info()

<class 'pandas.DataFrame'>
RangeIndex: 77736 entries, 0 to 77735
Data columns (total 19 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Unnamed: 0.1      77736 non-null  int64
 1   Unnamed: 0        77736 non-null  int64
 2   REF_AREA          77736 non-null  int64
 3   RESULT            77736 non-null  str
 4   TIME_PERIOD       77736 non-null  int64
 5   OBS_VALUE         77736 non-null  int64
 6   RESULT_DESC       77736 non-null  str
 7   anno_riferimento  77736 non-null  int64
 8   COD_RIP           77736 non-null  int64
 9   DEN_RIP           77736 non-null  str
 10  COD_REG           77736 non-null  int64
 11  DEN_REG           77736 non-null  str
 12  COD_UTS           77736 non-null  int64
 13  DEN_UTS           77736 non-null  str
 14  PRO_COM           77736 non-null  int64
 15  COMUNE            77736 non-null  str
 16  AREA_KMQ          77736 non-null  float64
 17  POP_RES           77736 non-null  int64
 18  POP_AL_KMQ        77736 non-null  float64
dtypes: float64(2), int64(11), str(6)
memory usage: 11.3 MB

In [78]:
df_incidenti_flat_an[
    df_incidenti_flat_an['anno_riferimento']==df_incidenti_flat_an['TIME_PERIOD']
    ].count()

Unnamed: 0.1        77736
Unnamed: 0          77736
REF_AREA            77736
RESULT              77736
TIME_PERIOD         77736
OBS_VALUE           77736
RESULT_DESC         77736
anno_riferimento    77736
COD_RIP             77736
DEN_RIP             77736
COD_REG             77736
DEN_REG             77736
COD_UTS             77736
DEN_UTS             77736
PRO_COM             77736
COMUNE              77736
AREA_KMQ            77736
POP_RES             77736
POP_AL_KMQ          77736
dtype: int64

In [79]:
df_incidenti_flat_an[
    df_incidenti_flat_an['anno_riferimento']!=df_incidenti_flat_an['TIME_PERIOD']
    ].count()

Unnamed: 0.1        0
Unnamed: 0          0
REF_AREA            0
RESULT              0
TIME_PERIOD         0
OBS_VALUE           0
RESULT_DESC         0
anno_riferimento    0
COD_RIP             0
DEN_RIP             0
COD_REG             0
DEN_REG             0
COD_UTS             0
DEN_UTS             0
PRO_COM             0
COMUNE              0
AREA_KMQ            0
POP_RES             0
POP_AL_KMQ          0
dtype: int64

In [80]:
df_incidenti_flat_an = df_incidenti_flat_an.drop('anno_riferimento', axis=1)

In [81]:
df_incidenti_flat_an[
    df_incidenti_flat_an['REF_AREA']==df_incidenti_flat_an['PRO_COM']
    ].count()

Unnamed: 0.1    77736
Unnamed: 0      77736
REF_AREA        77736
RESULT          77736
TIME_PERIOD     77736
OBS_VALUE       77736
RESULT_DESC     77736
COD_RIP         77736
DEN_RIP         77736
COD_REG         77736
DEN_REG         77736
COD_UTS         77736
DEN_UTS         77736
PRO_COM         77736
COMUNE          77736
AREA_KMQ        77736
POP_RES         77736
POP_AL_KMQ      77736
dtype: int64

In [82]:
df_incidenti_flat_an[
    df_incidenti_flat_an['REF_AREA']!=df_incidenti_flat_an['PRO_COM']
    ].count()

Unnamed: 0.1    0
Unnamed: 0      0
REF_AREA        0
RESULT          0
TIME_PERIOD     0
OBS_VALUE       0
RESULT_DESC     0
COD_RIP         0
DEN_RIP         0
COD_REG         0
DEN_REG         0
COD_UTS         0
DEN_UTS         0
PRO_COM         0
COMUNE          0
AREA_KMQ        0
POP_RES         0
POP_AL_KMQ      0
dtype: int64

In [83]:
df_incidenti_flat_an = df_incidenti_flat_an.drop('REF_AREA', axis=1)

In [84]:
df_incidenti_flat_an.columns

Index(['Unnamed: 0.1', 'Unnamed: 0', 'RESULT', 'TIME_PERIOD', 'OBS_VALUE',
       'RESULT_DESC', 'COD_RIP', 'DEN_RIP', 'COD_REG', 'DEN_REG', 'COD_UTS',
       'DEN_UTS', 'PRO_COM', 'COMUNE', 'AREA_KMQ', 'POP_RES', 'POP_AL_KMQ'],
      dtype='str')

In [85]:
#riprdino le colonne
df_incidenti_flat_an = df_incidenti_flat_an[[ 'TIME_PERIOD', 
        'COD_RIP', 'DEN_RIP', 'COD_REG', 'DEN_REG', 'COD_UTS',
       'DEN_UTS', 'PRO_COM', 'COMUNE', 'AREA_KMQ', 'POP_RES', 'POP_AL_KMQ','RESULT','RESULT_DESC','OBS_VALUE']]

In [86]:
df_incidenti_flat_an = df_incidenti_flat_an.reset_index()

In [87]:
df_incidenti_flat_an.head(5)

,index,TIME_PERIOD,COD_RIP,DEN_RIP,COD_REG,DEN_REG,COD_UTS,DEN_UTS,PRO_COM,COMUNE,AREA_KMQ,POP_RES,POP_AL_KMQ,RESULT,RESULT_DESC,OBS_VALUE
0,0,2015,1,Nord-ovest,1,Piemonte,201,Torino,1001,Agliè,13.1462,2701,205.46,F,Feriti,9
1,1,2016,1,Nord-ovest,1,Piemonte,201,Torino,1001,Agliè,13.1462,2644,201.12,F,Feriti,8
2,2,2018,1,Nord-ovest,1,Piemonte,201,Torino,1001,Agliè,13.1462,2658,202.19,F,Feriti,1
3,3,2019,1,Nord-ovest,1,Piemonte,201,Torino,1001,Agliè,13.1462,2634,200.36,F,Feriti,5
4,4,2020,1,Nord-ovest,1,Piemonte,201,Torino,1001,Agliè,13.1462,2621,199.37,F,Feriti,4

In [88]:
df_incidenti_flat_an.info()

<class 'pandas.DataFrame'>
RangeIndex: 77736 entries, 0 to 77735
Data columns (total 16 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   index        77736 non-null  int64
 1   TIME_PERIOD  77736 non-null  int64
 2   COD_RIP      77736 non-null  int64
 3   DEN_RIP      77736 non-null  str
 4   COD_REG      77736 non-null  int64
 5   DEN_REG      77736 non-null  str
 6   COD_UTS      77736 non-null  int64
 7   DEN_UTS      77736 non-null  str
 8   PRO_COM      77736 non-null  int64
 9   COMUNE       77736 non-null  str
 10  AREA_KMQ     77736 non-null  float64
 11  POP_RES      77736 non-null  int64
 12  POP_AL_KMQ   77736 non-null  float64
 13  RESULT       77736 non-null  str
 14  RESULT_DESC  77736 non-null  str
 15  OBS_VALUE    77736 non-null  int64
dtypes: float64(2), int64(8), str(6)
memory usage: 9.5 MB

In [89]:
df_incidenti_flat_an.TIME_PERIOD.unique()

array([2015, 2016, 2018, 2019, 2020, 2021, 2022, 2023, 2024, 2017])

In [90]:
#SALVO IL DATASET FINALE

pd_common.SalvaDataset(df_incidenti_flat_an, f"Incidenti_flat",False)

      path completo file:  c:\progetto_dataanalyst\progettofinale\Analisi/Incidenti_flat.csv
         Il file 'c:\progetto_dataanalyst\progettofinale\Analisi/Incidenti_flat.csv' esiste, per cui lo rimuovo
      Il file salvato c:\progetto_dataanalyst\progettofinale\Analisi/Incidenti_flat.csv